services:
  threat-dragon:
    image: owasp/threat-dragon:v2.6.0
    container_name: threat-dragon
    env_file:
      - ./.env
    volumes:
      - ./.env:/app/.env:ro
    ports:
      - "3000:3000"
    restart: unless-stopped
