services:
  threat-dragon:
    image: owasp/threat-dragon:${THREAT_DRAGON_TAG:-v2.6.0}
    platform: ${PLATFORM:-linux/amd64}
    container_name: threat-dragon
    env_file:
      - ./.env
    volumes:
      - ./.env:/app/.env:ro
    ports:
      - "3000:3000"
    restart: unless-stopped
